// export const ADD_TODO = "ADD_TODO";
// export const TOGGLE_TODO = "TOGGLE_TODO";
// export const DELETE_TODO = "DELETE_TODO";
export const EDIT_DB_TODO = "EDIT_DB_TODO";
export const GET_ALL_LATEST_TODOS_LOADING = 'GET_ALL_LATEST_TODOS_LOADING';
export const GET_ALL_LATEST_TODOS_FAILURE = 'GET_ALL_LATEST_TODOS_FAILURE';
